/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "gitlab.aibee.cn/platform/ai-scheduler/pkg/apis/resources/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeResourcePools implements ResourcePoolInterface
type FakeResourcePools struct {
	Fake *FakeResourcesV1alpha1
}

var resourcepoolsResource = schema.GroupVersionResource{Group: "resources", Version: "v1alpha1", Resource: "resourcepools"}

var resourcepoolsKind = schema.GroupVersionKind{Group: "resources", Version: "v1alpha1", Kind: "ResourcePool"}

// Get takes name of the resourcePool, and returns the corresponding resourcePool object, and an error if there is any.
func (c *FakeResourcePools) Get(name string, options v1.GetOptions) (result *v1alpha1.ResourcePool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(resourcepoolsResource, name), &v1alpha1.ResourcePool{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ResourcePool), err
}

// List takes label and field selectors, and returns the list of ResourcePools that match those selectors.
func (c *FakeResourcePools) List(opts v1.ListOptions) (result *v1alpha1.ResourcePoolList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(resourcepoolsResource, resourcepoolsKind, opts), &v1alpha1.ResourcePoolList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ResourcePoolList{ListMeta: obj.(*v1alpha1.ResourcePoolList).ListMeta}
	for _, item := range obj.(*v1alpha1.ResourcePoolList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested resourcePools.
func (c *FakeResourcePools) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(resourcepoolsResource, opts))
}

// Create takes the representation of a resourcePool and creates it.  Returns the server's representation of the resourcePool, and an error, if there is any.
func (c *FakeResourcePools) Create(resourcePool *v1alpha1.ResourcePool) (result *v1alpha1.ResourcePool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(resourcepoolsResource, resourcePool), &v1alpha1.ResourcePool{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ResourcePool), err
}

// Update takes the representation of a resourcePool and updates it. Returns the server's representation of the resourcePool, and an error, if there is any.
func (c *FakeResourcePools) Update(resourcePool *v1alpha1.ResourcePool) (result *v1alpha1.ResourcePool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(resourcepoolsResource, resourcePool), &v1alpha1.ResourcePool{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ResourcePool), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeResourcePools) UpdateStatus(resourcePool *v1alpha1.ResourcePool) (*v1alpha1.ResourcePool, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(resourcepoolsResource, "status", resourcePool), &v1alpha1.ResourcePool{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ResourcePool), err
}

// Delete takes name of the resourcePool and deletes it. Returns an error if one occurs.
func (c *FakeResourcePools) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(resourcepoolsResource, name), &v1alpha1.ResourcePool{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeResourcePools) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(resourcepoolsResource, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ResourcePoolList{})
	return err
}

// Patch applies the patch and returns the patched resourcePool.
func (c *FakeResourcePools) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ResourcePool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(resourcepoolsResource, name, pt, data, subresources...), &v1alpha1.ResourcePool{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ResourcePool), err
}
