/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "gitlab.aibee.cn/platform/ai-scheduler/pkg/apis/resources/v1alpha1"
	scheme "gitlab.aibee.cn/platform/ai-scheduler/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ResourcePoolsGetter has a method to return a ResourcePoolInterface.
// A group's client should implement this interface.
type ResourcePoolsGetter interface {
	ResourcePools() ResourcePoolInterface
}

// ResourcePoolInterface has methods to work with ResourcePool resources.
type ResourcePoolInterface interface {
	Create(*v1alpha1.ResourcePool) (*v1alpha1.ResourcePool, error)
	Update(*v1alpha1.ResourcePool) (*v1alpha1.ResourcePool, error)
	UpdateStatus(*v1alpha1.ResourcePool) (*v1alpha1.ResourcePool, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ResourcePool, error)
	List(opts v1.ListOptions) (*v1alpha1.ResourcePoolList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ResourcePool, err error)
	ResourcePoolExpansion
}

// resourcePools implements ResourcePoolInterface
type resourcePools struct {
	client rest.Interface
}

// newResourcePools returns a ResourcePools
func newResourcePools(c *ResourcesV1alpha1Client) *resourcePools {
	return &resourcePools{
		client: c.RESTClient(),
	}
}

// Get takes name of the resourcePool, and returns the corresponding resourcePool object, and an error if there is any.
func (c *resourcePools) Get(name string, options v1.GetOptions) (result *v1alpha1.ResourcePool, err error) {
	result = &v1alpha1.ResourcePool{}
	err = c.client.Get().
		Resource("resourcepools").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ResourcePools that match those selectors.
func (c *resourcePools) List(opts v1.ListOptions) (result *v1alpha1.ResourcePoolList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ResourcePoolList{}
	err = c.client.Get().
		Resource("resourcepools").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested resourcePools.
func (c *resourcePools) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("resourcepools").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a resourcePool and creates it.  Returns the server's representation of the resourcePool, and an error, if there is any.
func (c *resourcePools) Create(resourcePool *v1alpha1.ResourcePool) (result *v1alpha1.ResourcePool, err error) {
	result = &v1alpha1.ResourcePool{}
	err = c.client.Post().
		Resource("resourcepools").
		Body(resourcePool).
		Do().
		Into(result)
	return
}

// Update takes the representation of a resourcePool and updates it. Returns the server's representation of the resourcePool, and an error, if there is any.
func (c *resourcePools) Update(resourcePool *v1alpha1.ResourcePool) (result *v1alpha1.ResourcePool, err error) {
	result = &v1alpha1.ResourcePool{}
	err = c.client.Put().
		Resource("resourcepools").
		Name(resourcePool.Name).
		Body(resourcePool).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *resourcePools) UpdateStatus(resourcePool *v1alpha1.ResourcePool) (result *v1alpha1.ResourcePool, err error) {
	result = &v1alpha1.ResourcePool{}
	err = c.client.Put().
		Resource("resourcepools").
		Name(resourcePool.Name).
		SubResource("status").
		Body(resourcePool).
		Do().
		Into(result)
	return
}

// Delete takes name of the resourcePool and deletes it. Returns an error if one occurs.
func (c *resourcePools) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("resourcepools").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *resourcePools) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("resourcepools").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched resourcePool.
func (c *resourcePools) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ResourcePool, err error) {
	result = &v1alpha1.ResourcePool{}
	err = c.client.Patch(pt).
		Resource("resourcepools").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
