# Default values for ai-scheduler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: registry.aibee.cn/platform/kubernetes/ai-scheduler
  tag: v0.1.0
  pullPolicy: IfNotPresent
resources:
  limits:
    cpu: 2000m
    memory: 2048Mi
  requests:
    cpu: 2000m
    memory: 2048Mi

