# Default values for ai-scheduler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 3
image:
  repository: registry.aibee.cn/platform/kubernetes/ai-scheduler
  tag: v0.1.0-alpha1
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 2000m
    memory: 2048Mi
  requests:
    cpu: 2000m
    memory: 2048Mi

securePort: 20888
healthzPort: 20999

disablePreemption: true

leaderElect: true
leaseDuration: "15s"
renewDeadline: "10s"
retryPeriod: "2s"

