# Default values for ai-scheduler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 3
image:
  repository: registry.aibee.cn/platform/kubernetes/ai-scheduler
  pullPolicy: IfNotPresent
restartPolicy: Always

resources:
  limits:
    cpu: 4
    memory: 4Gi
  requests:
    cpu: 4
    memory: 4Gi

securePort: 20888
healthzPort: 20999

disablePreemption: true

leaderElect: true
leaseDuration: "15s"
renewDeadline: "10s"
retryPeriod: "2s"

