apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: kube-system
data:
  kubeconfig: |
{{- if eq .Values.cluster "bj"}}
{{ toYaml .Values.bjConfig | indent 4 }}
{{- end}}
{{- if eq .Values.cluster "gz"}}
{{ toYaml .Values.gzConfig | indent 4 }}
{{- end}}
{{- if eq .Values.cluster "sh"}}
{{ toYaml .Values.shConfig | indent 4 }}
{{- end}}
{{- if eq .Values.cluster "qa"}}
{{ toYaml .Values.qaConfig | indent 4 }}
{{- end}}
{{- if eq .Values.cluster "etcd"}}
{{ toYaml .Values.etcdConfig | indent 4 }}
{{- end}}
  kubeschedulerconfig.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1alpha1
    kind: KubeSchedulerConfiguration
    algorithmSource:
      provider: {{ .Values.algorithmSource.provider }}
    clientConnection:
      kubeconfig: "/etc/kubernetes/kubeconfig"
      burst: {{ .Values.clientConnection.burst }}
      qps: {{ .Values.clientConnection.qps }}
    leaderElection:
      leaderElect: {{ .Values.leaderElect }}
      leaseDuration: {{ .Values.leaseDuration }}
      renewDeadline: {{ .Values.renewDeadline }}
      retryPeriod: {{ .Values.retryPeriod }}
      lockObjectNamespace: kube-system
      lockObjectName: {{ .Chart.Name }}
    schedulerName: {{ .Chart.Name }}
    healthzBindAddress: 0.0.0.0:{{ .Values.healthzPort }}
    metricsBindAddress: 0.0.0.0:{{ .Values.healthzPort }}
    disablePreemption: {{ .Values.disablePreemption }}
