apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pools.resource.aibee.cn
  annotations:
    "helm.sh/hook": "crd-install"
spec:
  group: resource.aibee.cn
  versions:
    - name: v1alpha1
      served: true
      storage: true
  names:
    kind: Pool
    plural: pools
    singular: pool
    shortNames:
      - pool
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            weight.value:
              format: int32
              type: integer
            disablePreemption:
              format: bool
              type: boolean
            disableBorrowing:
              format: bool
              type: boolean
            disableSharing:
              format: bool
              type: boolean
          type: object
      type: object
