apiVersion: resource.aibee.cn/v1alpha1
kind: Pool
metadata:
  name: cpu-pool
spec:
  nodeSelector:
    matchLabels:
      cpu: "true"
  disablePreemption: false
  disableBorrowing: false
  disableSharing: false
---
apiVersion: resource.aibee.cn/v1alpha1
kind: Pool
metadata:
  name: gpu-pool
spec:
  nodeSelector:
    matchLabels:
      gpu: "true"
  disablePreemption: false
  disableBorrowing: false
  disableSharing: false
