apiVersion: batch/v1
kind: Job
metadata:
  name: test-job1
spec:
  completions: 100
  parallelism: 100
  activeDeadlineSeconds: 10000
  template:
    metadata:
      name: test-job1
      annotations:
        resource.aibee.cn/pool: tests
    spec:
      schedulerName: ai-scheduler
      containers:
        - name: pi
          image: perl
          command: ["perl"]
          args: ["-Mbignum=bpi", "-wle", "print bpi(2000)"]
          resources:
            limits:
              cpu: 8
              memory: 100M
            requests:
              cpu: 8
              memory: 100M
      restartPolicy: Never
  backoffLimit: 1
