apiVersion: batch/v1
kind: Job
metadata:
  name: test-job1
spec:
  completions: 10000
  parallelism: 10000
  activeDeadlineSeconds: 10000
  template:
    metadata:
      name: test-job1
      annotations:
        resource.aibee.cn/pool: test-pool
    spec:
      schedulerName: ai-scheduler
      containers:
        - name: pi
          image: perl
          command: ["perl"]
          args: ["-Mbignum=bpi", "-wle", "print bpi(2000)"]
          resources:
            limits:
              cpu: 100m
              memory: 100M
            requests:
              cpu: 100m
              memory: 100M
      restartPolicy: Never
  backoffLimit: 1
