apiVersion: batch/v1
kind: Job
metadata:
  name: test-job4
spec:
  parallelism: 1
  template:
    metadata:
      name: test-job4
      annotations:
        resource.aibee.cn/pool: prod-gpu-pool
    spec:
      schedulerName: ai-scheduler
      containers:
        - name: pi
          image: perl
          command: ["perl"]
          args: ["-Mbignum=bpi", "-wle", "print bpi(20000)"]
          resources:
            limits:
              cpu: 100m
              memory: 100M
            requests:
              cpu: 100m
              memory: 100M
      restartPolicy: Never
  backoffLimit: 1