apiVersion: batch/v1
kind: Job
metadata:
  name: test-job1
spec:
  parallelism: 10000
  template:
    metadata:
      name: test-job1
      annotations:
        resource.aibee.cn/pool: cpu-pool
    spec:
      schedulerName: ai-scheduler
      containers:
        - name: pi
          image: perl
          command: ["perl"]
          args: ["-Mbignum=bpi", "-wle", "print bpi(20000)"]
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1000m
              memory: 100M
              "nvidia.com/gpu": "1"
            requests:
              cpu: 1000m
              memory: 100M
              "nvidia.com/gpu": "1"
      restartPolicy: Never
  backoffLimit: 1