apiVersion: resource.aibee.cn/v1alpha1
kind: Pool
metadata:
  name: test-pool
spec:
  nodeSelector:
    matchLabels:
      test-pool: "true"
  priority: 5
  disablePreemption: false
  disableBorrowing: false
  disableSharing: false