apiVersion: resource.aibee.cn/v1alpha1
kind: Pool
metadata:
  name: test-pool1
spec:
  nodeSelector:
    matchLabels:
      gpu: "true"

  supportResources:
    - "cpu"

  weight:
    cpu: 2
    nvidia.com/gpu: 0

#  quota:
#    cpu: "4"
#    nvidia.com/gpu: "10"

  priorites:
    - name: "MostRequestedPriority"
      weight: 1

  disablePreemption: false
  disableBorrowing: false
  disableSharing: false
---
apiVersion: resource.aibee.cn/v1alpha1
kind: Pool
metadata:
  name: test-pool2
spec:
  nodeSelector:
    matchLabels:
      cpu: "true"

#  supportResources:
#    - "nvidia.com/gpu"

  weight:
    cpu: 1
    nvidia.com/gpu: 1

#  quota:
#    cpu: "5"
#    nvidia.com/gpu: "10"

  priorites:
    - name: "MostRequestedPriority"
      weight: 1

  disablePreemption: false
  disableBorrowing: false
  disableSharing: false